### ISSUE TITLE
Please credit me in the savebot commit message.

### ISSUE THREAD

**Issue by kit-solent** [vindognz/Dementris#4]
Can you change the savebot commit message so that it includes my github username (kit-solent). Plz plz plz pl zplz plz zp lzp lz pzlzpzlp. If you do then I will give you my large file encryption program I made. It's verry tasty.

**Comment by kit-solent** [comment]
plz plz plz plz

**Comment by Nicomo-Cosca** [comment]
I think this guy needs credit if he made the tool. Nice game btw.

**Comment by vindognz** [comment]
the savebot commit msgs are now credited to github.com/vindognz

**Comment by kit-solent** [comment]
:( Don't make me unstar the repo.

**Comment by vindognz** [comment]
@kit-solent i hope you are happy now.

**Comment by kit-solent** [comment]
![x](https://github.com/user-attachments/assets/a8648a6a-6c0b-4d9a-9615-942a1e24bf95)

**Comment by kit-solent** [comment]
And your repo will remain forever starred. ⭐
