### ISSUE TITLE
readme is outdated

### ISSUE THREAD

**Issue by vindognz** [vindognz/Dementris#5]
you should really remove the random keys from README that you deleted ages ago. like mute etc.

**Comment by Nicomo-Cosca** [comment]
This removes all the volume related keys from README: [https://github.com/vindognz/Dementris/pull/6#issue-2554006941](https://github.com/vindognz/Dementris/pull/6#issue-2554006941)

**Comment by vindognz** [comment]
@vindognz i did it!
